" Thanks to PeepCode for the starting point.

set guifont=Inconsolata:h14       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set lines=50 columns=150          " Window dimensions.

" set guioptions-=r                 " Don't show right scrollbar

