set guifont=Inconsolata:h14       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=35 columns=110          " Window dimensions.
set list

" Uncomment to use.
" set guioptions-=r               " Don't show right scrollbar
