" Shortcut to rapidly toggle `set list`
"nmap <leader>l :set list!<CR>
 
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

set ts=4
set list
set number

colorscheme autumnleaf

