[[ -e ~/.bashrc ]] && emulate sh -c 'source ~/.bashrc'

SAVEHIST=10000
HISTFILE=~/.zsh_history

autoload -Uz compinit && compinit # for Git (and other things?)
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:stash show yes
prompt pure

if [ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    . /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
